# Generated by Django 5.1.5 on 2025-01-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deu_date',
            new_name='due_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], default='L', max_length=1)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tasks.task')),
            ],
        ),
    ]
